In [2]:
import pandas as pd
import torch

# 1. 读取 CSV 文件
df = pd.read_csv("F:\PythonCode\\data\house_tiny.csv")

# 2. 打印前几行 (默认前 5 行)
print("--- 数据的预览 ---")
print(df.head())

# 3. 如果需要转换为 PyTorch Tensor
# 假设你的数据全是数值型
tensor_data = torch.tensor(df.values)
print("\n--- 转换后的 Tensor 形状 ---")
print(tensor_data.shape)

OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。 Error loading "D:\anaconda\envs\d2l-zh\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [32]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x * y, x - y, x / y, x**y, torch.exp(x)

(tensor([ 3.,  4.,  6., 10.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]))

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Z = torch.reshape(X, (12, ))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
X[:, -1].reshape((3, -1)), X

(tensor([[ 3.],
         [ 7.],
         [11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [57]:
a = torch.arange(12)
b = a.reshape((3, 4))
b[:] = 2
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
import pandas as pd

data = pd.read_csv(data_file)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [49]:
# 方法：直接计算均值并填充
data['NumRooms'] = data['NumRooms'].fillna(data['NumRooms'].mean())
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [52]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [53]:
# 方法：在取 values 时强制转换为 float 类型
X, y = torch.tensor(inputs.values.astype(float)), torch.tensor(outputs.values)
X, y, type(inputs.values)

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]),
 numpy.ndarray)

In [1]:
X = torch.arange(24).reshape((2, 3, 4))
X

NameError: name 'torch' is not defined

In [64]:
A = torch.arange(12, dtype=float).reshape((3, 4))
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [65]:
sum_A = A.sum(axis=0, keepdims=True)
sum_A

tensor([[12., 15., 18., 21.]], dtype=torch.float64)